# basic information
site_name: why的个人网站
site_url: https://falling-leaf.github.io/notebook/
site_author: 王昊元
site_description: why的个人网站

nav: 
- 首页: 
  - home: index.md
  - 软工/工高课程简述及结构: introduction.md
- 数理基础:
  - ./math/index.md
  - 离散数学及其应用:
    - ./math/DMIA/index.md
  - 大学物理:
    - ./math/PHYSICS/index.md
  - 微积分:
    - ./math/CALCULUS/index.md
  - 线性代数:
    - ./math/LA/index.md
  - 数学建模:
    - ./math/MM/index.md
- 计算机:
  - ./computer/index.md
#  - 计算机构成/计算机系统概论:
#  - 计算机构成/数字逻辑设计:
#  - 计算机构成/计算机系统原理:
#  - 编程语言/C程序设计基础:
#  - 编程语言/程序设计专题:
#  - 编程语言/面向对象程序设计:
#    - ./computer/OOP/index.md
  - 算法/数据结构基础:
    - ./computer/FDS/index.md
- 通识:
  - ./extra/index.md
  - 德语I:
    - ./extra/GERMANY/index.md
- 音乐:
  - ./music/index.md
  - 演奏曲目: ./music/PLAY.md
  - 原创曲目: ./music/COMPOSE.md
  - 个人小记: ./music/note.md
#- 二次元:
#  - 番剧:
#  - 游戏（游戏也能算二次元吗）:



theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
    - media: "(prefers-color-scheme:light)"
      scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式
  language: 'zh'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
