# basic information
site_name: why的个人网站
site_url: https://falling-leaf.github.io/notebook/
site_author: 王昊元
site_description: why的个人网站

nav: 
- 首页: 
  - home: index.md
  - 软工/工高课程简述及结构: introduction.md
- 数理基础:
  - ./math/index.md
  #- 离散数学及其应用:
  #  - ./math/DMIA/index.md
  #- 大学物理:
  #  - ./math/PHYSICS/index.md
  #- 微积分:
  #  - ./math/CALCULUS/index.md
  #- 线性代数:
  #  - ./math/LA/index.md
  #- 数学建模:
  #  - ./math/MM/index.md
- 计算机:
  - ./computer/index.md
  - 计算机图形学(GAMES101):
    - lecture 1: ./computer/GAMES101/lecture_1.md
    - lecture 2: ./computer/GAMES101/lecture_2.md
    - lecture 3: ./computer/GAMES101/lecture_3.md
    - lecture 4: ./computer/GAMES101/lecture_4.md
  - 操作系统:
    - class 1: ./computer/OS/class1.md
    - class 2: ./computer/OS/class2.md
    - class 3: ./computer/OS/class3.md
    - class 4: ./computer/OS/class4.md
    - class 5: ./computer/OS/class5.md
    - class 6: ./computer/OS/class6.md
    - class 7: ./computer/OS/class7.md
  - 计算机网络:
    - class 1: ./computer/CN/class1.md
    - class 2: ./computer/CN/class2.md
    - class 3: ./computer/CN/class3.md
    - class 4: ./computer/CN/class4.md
    - class 5: ./computer/CN/class5.md
  - +工具/ElasticSearch:
    - ./computer/ES/ES.md
  - +工具/静态网页设置:
    - ./computer/PAGES/pages.md
- 音乐:
  - ./music/index.md
  - 演奏曲目: ./music/PLAY.md
  - 原创曲目: ./music/COMPOSE.md
  - 个人小记: ./music/note.md
#- 二次元:
#  - 番剧:
#  - 游戏（游戏也能算二次元吗）:


# 在此感谢jpgg的开源代码！jpgg我的超人ovo
theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
    - media: "(prefers-color-scheme:light)"
      scheme: default
      primary: green
      accent: yellow
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式
  language: 'zh'

  features:
    # - header.autohide #自动隐藏头栏
    # - announce.dismiss # 公告栏
    # - navigation.instant #这玩意跟公式爆了
    - navigation.tracking # 在url中使用标题定位锚点
    - navigation.path # 显示当前路径
    - navigation.prune # 侧边栏自动折叠
    - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    # - navigation.tabs.sticky # 滚动是隐藏顶部nav，需要配合navigation.tabs使用
    - navigation.indexes # 指定节点index pages ，跟instant不兼容
    - navigation.top # 一键回顶部
    - navigation.footer # 底部导航
    - search.highlight # 搜索高亮
    - search.suggest # 搜索建议
    - toc.follow # toc 跟随
    - content.code.annotate # 代码行号
    - content.code.copy # 代码复制

  language: 'zh'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  #logo: ./images/logo.png
  #favicon: ./images/icon.jpg

#plugins:
  #- statistics:
      #words_per_minute: 200
  #- search:
  #    lang:
  #      - zh
  #      - en
  #      - ja
  #    separator: '[\s\u200b\-]'
#  - glightbox #git action跑不起来
  #- git-revision-date-localized:
  #    type: datetime
  #    timezone: Asia/Shanghai
  #    locale: zh
  #    enable_creation_date: true
  #    exclude:
  #      - index.md
  # - heti: 
  #   disable_serve: false
  #   extra_skipped_class:
  #     - arithmatex


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
